name: pbl3
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2
  cloudinary: ^1.2.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/anhmau.jpg
    - assets/images/warning.png